services:
  postgres:
    image: postgres:16
    container_name: container-postgres-ms-clinica-agendamento
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - clinica-net
    ports:
      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-app-ms-clinica
    restart: always
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "broker:29092"
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - clinica-net
    ports:
      - "9001:9001"
    depends_on:
      - postgres

networks:
  clinica-net:
    external: true